name: Deploy CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install vsce and open vsx
        run: |
          npm install -g @vscode/vsce
          npm install -g ovsx

      - name: yarn
        run: yarn

      - name: VSCE Publish
        run: vsce publish --yarn -p $env:VSCE_PAT
        env:
          VSCE_PAT: ${{ secrets.VSCE_PRETTYXML }}

      - name: Open VSX Publish
        run: npx ovsx publish --yarn -p $env:OPEN_VSX_PAT
        env:
          OPEN_VSX_PAT: ${{ secrets.OPENVSX }}
